from typing import Protocol

from ..models.dto.local_article import LocalArticleCatalogItem


class LocalArticleRepository(Protocol):
    """本地长文库持久化端口。"""

    def list_articles(self) -> list[LocalArticleCatalogItem]: ...

    def get_article(self, article_id: str) -> LocalArticleCatalogItem: ...

    def resolve_article_path(self, article_id: str) -> str | None: ...

    def load_article_content(self, article_id: str) -> str: ...

    def load_article_segment(self, article_id: str, start: int, length: int) -> str: ...

    def count_article_chars(self, article_id: str) -> int: ...

    def save_current_segment(self, article_id: str, segment_index: int) -> None: ...

    def load_current_segment(self, article_id: str) -> int | None: ...

    def delete_article(self, article_id: str) -> bool: ...

    def rename_article(self, article_id: str, new_title: str) -> bool: ...
